package LibraryModels;
// Generated May 11, 2020 11:33:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookid;
     private String title;
     private String publishingHouse;
     private Date dateOfPublication;
     private String author;
     private Integer pages;
      private String category;

    public Book() {
    }

	
    public Book(String bookid) {
        this.bookid = bookid;
    }
    public Book(String bookid, String title, String publishingHouse, Date dateOfPublication, String author, Integer pages, String category) {
       this.bookid = bookid;
       this.title = title;
       this.publishingHouse = publishingHouse;
       this.dateOfPublication = dateOfPublication;
       this.author = author;
       this.pages = pages;
       this.category=category;
    }
   
    public String getBookid() {
        return this.bookid;
    }
    
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }
    public Date getDateOfPublication() {
        return this.dateOfPublication;
    }
    
    public void setDateOfPublication(Date dateOfPublication) {
        this.dateOfPublication = dateOfPublication;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }


public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category =category ;
    }

}


