package LibraryModels;
// Generated May 11, 2020 11:33:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private String id;
     private String client;
     private String book;
     private Date date;
     private String operationCategory;

    public Operation() {
    }

	
    public Operation(String id) {
        this.id = id;
    }
    public Operation(String id, String client, String book, Date date, String operationCategory) {
       this.id = id;
       this.client = client;
       this.book = book;
       this.date = date;
       this.operationCategory = operationCategory;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public String getBook() {
        return this.book;
    }
    
    public void setBook(String book) {
        this.book = book;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getOperationCategory() {
        return this.operationCategory;
    }
    
    public void setOperationCategory(String operationCategory) {
        this.operationCategory = operationCategory;
    }




}


